In [4]:
import numpy as np
from scipy import linalg

D=np.mat([[3,4],[5,6]])
print(D)
b=np.mat([[1],[2]])
print(b)

[[3 4]
 [5 6]]
[[1]
 [2]]


In [6]:
e=D @b
print(e)

[[11]
 [17]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [7]:
C=np.mat([[3,0,2],[2,0,-2],[0,1,1]])
print(C)

[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]


In [8]:
invC=C.I
print(invC)

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


In [9]:
print(C@invC)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
