In [1]:
import numpy as np
from scipy import linalg

Z=np.mat([[1,1,0,0],[1,1,0,0],[1,1,0,0],[1,0,1,0],[1,0,1,0],[1,0,0,1],[1,0,0,1],[1,0,0,1]])

matrixA=(Z.T@Z).I

print(matrixA)

print(linalg.det(Z.T@Z))

[[ 4.50359963e+15 -4.50359963e+15 -4.50359963e+15 -4.50359963e+15]
 [-4.50359963e+15  4.50359963e+15  4.50359963e+15  4.50359963e+15]
 [-4.50359963e+15  4.50359963e+15  4.50359963e+15  4.50359963e+15]
 [-4.50359963e+15  4.50359963e+15  4.50359963e+15  4.50359963e+15]]
3.9968028886505635e-15


In [7]:
X=np.mat([[1,1,0,0],[1,1,0,0],[1,1,0,0],[1,0,1,0],[1,0,1,0],[1,0,0,1],[1,0,0,1],[1,0,1,1]])

print(linalg.det(X.T@X))

matrixB=(X.T@X).I
print(matrixB)


12.000000000000007
[[ 2.         -2.         -1.5        -1.5       ]
 [-2.          2.33333333  1.5         1.5       ]
 [-1.5         1.5         1.5         1.        ]
 [-1.5         1.5         1.          1.5       ]]
